### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by Klortho** [crowsonkb/SublimeGPG#3]
You wrote:

> The essential flaw was in Package Control's auto-update mechanism.

I was surprised to read this, and I'm wondering, is it true of any ST package I install? I mean, not that they could steal my encrypted messages, but that, basically, they could run arbitrary code on my machine? I googled around a bit, but couldn't find a clear answer.

**Comment by Klortho** [comment]
> The entire thing was a stupid idea.

No, it wasn't.

**Comment by crowsonkb** [comment]
I got worried that someone could push code out that transparently stole encrypted messages or something. The thing is, the changes allowing them to do so would be *visible in the github repo*, so they'd have to obfuscate it a bit, but it's not *impossible*. Also if someone hacked my github account they could do this because (at least when this project was active) Package Control didn't enforce gpg signing of commits/tags or even pay attention to whether a release tag was signed or not. Signed tags exist for a reason and IMO it is irresponsible to allow auto-updating to an unsigned tag, in case of github account hacks/password theft and the like. It's much harder to fake a gpg signature, it basically requires hacking your user account on your computer at minimum.

Also, I was going through a depressive period at the time and thought no one had any intrinsic reason to trust *me* specifically.
